[package]
name = "qbit"
version = "0.2.3"
edition = "2024"
description = "A wrapper for qBittorrent Web API"
keywords = ["qbit", "qbittorrent", "api", "torrent"]
categories = ["api-bindings"]
repository = "https://github.com/Mattress237/qbittorrent-webui-api"
documentation = "https://docs.rs/qbit"
readme = "README.md"
authors = ["Mattress <mattress@mattress.no>"]
license = "MIT"

[features]
default = []
qBittorrent-5_3 = []
qBittorrent-5_1 = []

[dependencies]
reqwest = { version = "0.13.4", features = [
    "json",
    "multipart",
    "query",
    "form",
], default-features = false }
tokio = { version = "1.53.1", features = ["sync"], default-features = false }
serde = { version = "1.0.229", features = ["derive"], default-features = false }
serde_json = { version = "1.0.151", default-features = false }
serde_repr = { version = "0.1.21", default-features = false }
url = { version = "2.5.8", default-features = false }
derive_builder = { version = "0.20.2", features = ["alloc"], default-features = false }
bytes = { version = "1.12.1", default-features = false }

[dev-dependencies]
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"], default-features = false }
dotenv = { version = "0.15.0", default-features = false }
rand = { version = "0.10.2", features = ["thread_rng"] , default-features = false}

[lints.clippy]
uninlined_format_args = "allow"

# [lints.rust]
# missing_docs = "deny"
