on:
  push:
  pull_request:

jobs:
  Run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install qbittorrent-nox
        # Source: https://github.com/userdocs/qbittorrent-nox-static
        run: |
          mkdir -p ~/bin && source ~/.profile
          wget -qO ~/bin/qbittorrent-nox https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/x86_64-qbittorrent-nox
          chmod 700 ~/bin/qbittorrent-nox

      - name: Debug version
        run: ~/bin/qbittorrent-nox -v

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: |
          ~/bin/qbittorrent-nox &
          cargo test
