on:
  push:
  pull_request:

jobs:
  Run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install qbittorrent-nox
        run: sudo apt install qbittorrent-nox

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          cargo test
