on:
  push:
  pull_request:

jobs:
  Run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install qbittorrent-nox
        run: sudo apt install qbittorrent-nox

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Start qbittorrent-nox in background
        run: qbittorrent-nox &

      - name: Run tests
        run: |
          cargo test
